# Generated by Django 4.1.2 on 2022-10-26 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_projectrate_project_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrate',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='projects.project'),
        ),
    ]
