# Generated by Django 4.1.2 on 2022-10-08 08:51

import crowd_fund_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=11, validators=[crowd_fund_app.models.mobile_validator])),
                ('picture', models.ImageField(null=True, upload_to='crowd_fund_app/media/crowd_fund_app/images/users/')),
                ('status', models.CharField(choices=[('inactive', 'Inactive'), ('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended')], max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('details', models.TextField(max_length=1024)),
                ('total_target', models.FloatField(validators=[crowd_fund_app.models.greater_than_zero_validator])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ManyToManyField(related_name='projects', to='crowd_fund_app.projectcategory')),
                ('tags', models.ManyToManyField(related_name='projects', to='crowd_fund_app.projecttags')),
                ('user', models.ManyToManyField(related_name='projects', to='crowd_fund_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(null=True, upload_to='crowd_fund_app/media/crowd_fund_app/images/projects/')),
                ('project', models.ManyToManyField(related_name='images', to='crowd_fund_app.project')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(validators=[crowd_fund_app.models.greater_than_zero_validator])),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='crowd_fund_app.project')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='crowd_fund_app.user')),
            ],
        ),
    ]
