# Generated by Django 4.1.2 on 2022-10-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowd_fund_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('inactive', 'Inactive'), ('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended')], default='pending', max_length=9),
        ),
    ]
