# Generated by Django 4.1.2 on 2022-11-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowd_fund_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='picture',
            field=models.ImageField(max_length=200, null=True, upload_to='crowd_fund_app/images/users/'),
        ),
    ]
