# Generated by Django 4.1.2 on 2022-11-04 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowd_fund_app', '0002_alter_customuser_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='facebook_profile',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
