# Generated by Django 4.1.2 on 2022-11-04 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowd_fund_app', '0003_alter_customuser_facebook_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='facebook_profile',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='picture',
            field=models.ImageField(max_length=500, null=True, upload_to='crowd_fund_app/images/users/'),
        ),
    ]
